<a href="https://colab.research.google.com/github/julianovale/BB_Evolution/blob/main/0011_AluraBB_RedesNeurais_DL_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

### 1. transformando uma lista em um tensor
### 2. tipos (mais comuns) de tensor

In [ ]:
lista = [[1,2,3],
         [4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)
print()

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)
print()

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)
print()

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


### 3. transformando array numpy em tensor

In [ ]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)

[[0.74046841 0.02534408 0.21315688 0.49919017]
 [0.92243622 0.98688245 0.15262246 0.78888436]
 [0.02195713 0.9891748  0.5224067  0.45505407]]
float64
tensor([[0.7405, 0.0253, 0.2132, 0.4992],
        [0.9224, 0.9869, 0.1526, 0.7889],
        [0.0220, 0.9892, 0.5224, 0.4551]], dtype=torch.float64)
torch.float64


### 4. Gerando alguns tipos de tensores

In [ ]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3) # distribuição normal

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.4550,  0.1043,  1.9313],
        [ 0.1965,  0.2660,  0.7449],
        [-0.8233,  0.3073,  1.4318]])


### 5. de tensor para array numpy

In [ ]:
arr = tnsr.data.numpy()
print(arr)
print(type(arr))
print(type(tnsr))

[[ 0.4550155   0.10427653  1.9313488 ]
 [ 0.19650447  0.2660356   0.7449128 ]
 [-0.82333446  0.30727184  1.4317571 ]]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


### 6. Indexação

In [ ]:
print(tnsr)
print()
tnsr[0,2] = 100
print(tnsr)

tensor([[ 0.4550,  0.1043,  1.9313],
        [ 0.1965,  0.2660,  0.7449],
        [-0.8233,  0.3073,  1.4318]])

tensor([[  0.4550,   0.1043, 100.0000],
        [  0.1965,   0.2660,   0.7449],
        [ -0.8233,   0.3073,   1.4318]])


In [ ]:
print(tnsr[0:2,:]) # [linha, coluna]
print()
print(tnsr[:,1])
print(tnsr[:,1].size())

tensor([[  0.4550,   0.1043, 100.0000],
        [  0.1965,   0.2660,   0.7449]])

tensor([0.1043, 0.2660, 0.3073])
torch.Size([3])


In [ ]:
print(tnsr[0,2])
print(tnsr[0,2].size()) # também será um tensor (de dimensão 0)

tensor(100.)
torch.Size([])


### 7. Operações com tensor

In [ ]:
# as dimensoes têm que bater
tns1 = torch.randn(2,3)
tns2 = torch.ones(2,3)

print(tns1)
print(tns2)

print(tns1+tns2)
print(tns1*tns2) # operação ponto a ponto, não é como uma multiplicação de matrizes
print()

print(torch.mm(tns1, tns2.T)) # para fazer multiplicação de tensores como matrizes esse é o caminho

tensor([[ 0.1167,  0.9065,  0.6682],
        [-0.4500, -2.0525,  2.0095]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.1167,  1.9065,  1.6682],
        [ 0.5500, -1.0525,  3.0095]])
tensor([[ 0.1167,  0.9065,  0.6682],
        [-0.4500, -2.0525,  2.0095]])

tensor([[ 1.6914,  1.6914],
        [-0.4930, -0.4930]])


### 8. Size e view

In [ ]:
print(tns1.size())

torch.Size([2, 3])


In [ ]:
tns = torch.randn(2,2,3)
print(tns)

print()
print(tns.size())
tns = tns.view(12)
print(tns)
print()

tns = tns.view(3,4)
print(tns)

tensor([[[-1.8108,  0.6978,  1.3893],
         [ 0.6521, -0.6996, -0.7041]],

        [[-0.3054,  1.1698, -1.5601],
         [-0.2956,  0.5492, -0.1187]]])

torch.Size([2, 2, 3])
tensor([-1.8108,  0.6978,  1.3893,  0.6521, -0.6996, -0.7041, -0.3054,  1.1698,
        -1.5601, -0.2956,  0.5492, -0.1187])

tensor([[-1.8108,  0.6978,  1.3893,  0.6521],
        [-0.6996, -0.7041, -0.3054,  1.1698],
        [-1.5601, -0.2956,  0.5492, -0.1187]])


### 9. GPU Cast

In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

cuda


In [ ]:
tns = tns.to(device)
print(tns)

tensor([[-1.8108,  0.6978,  1.3893,  0.6521],
        [-0.6996, -0.7041, -0.3054,  1.1698],
        [-1.5601, -0.2956,  0.5492, -0.1187]], device='cuda:0')


### 10. Exercício

In [ ]:

tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())
print(resultado)

torch.Size([5, 8])
tensor([[ 0.0374,  1.5182, -3.8493, -2.1824, -0.7933, -4.0922, -4.8062,  2.6660],
        [ 1.2036,  0.4030, -4.0945, -1.2854,  1.8143, -2.5648, -3.4778,  2.6995],
        [ 1.2536,  4.2302,  2.4340,  2.0527,  3.6577,  3.6450,  4.2730, -1.1120],
        [ 0.8574, -1.0981, -1.5166, -0.7724, -3.3857, -2.9011, -4.7401, -1.3009],
        [-2.5485, -2.7367, -2.1413, -2.5160, -2.8202, -3.3366, -2.6756,  2.7080]])
