<a href="https://colab.research.google.com/github/julianovale/BB_Evolution/blob/main/0033_AluraBB_ClassificacaoTrasPanos03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
if not os.path.isfile('/content/Cursos.csv'):
  ! wget https://raw.githubusercontent.com/julianovale/BB_Evolution/main/Arquivos/Cursos.csv
! ls

--2022-01-03 10:28:34--  https://raw.githubusercontent.com/julianovale/BB_Evolution/main/Arquivos/Cursos.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13897 (14K) [text/plain]
Saving to: ‘Cursos.csv’

Cursos.csv          100%[===================>]  13.57K  --.-KB/s    in 0s      

2022-01-03 10:28:34 (103 MB/s) - ‘Cursos.csv’ saved [13897/13897]

Cursos.csv  sample_data


In [2]:
import csv

def carregar_buscas():

    X = []
    Y = []

    arquivo = open('Cursos.csv', 'r')
    leitor = csv.reader(arquivo)

    next(leitor)

    for home, busca, logado, comprou in leitor:

        dado = ([int(home), busca, int(logado)])
        X.append(dado)
        Y.append(int(comprou))

    return X, Y

In [3]:
X, Y = carregar_buscas()

In [4]:
X[0:5]

[[0, 'algoritmos', 1],
 [0, 'java', 0],
 [1, 'algoritmos', 0],
 [1, 'ruby', 1],
 [1, 'ruby', 0]]

In [5]:
Y[0:5]

[1, 1, 1, 0, 1]

In [6]:
import pandas as pd
df = pd.read_csv('Cursos.csv')
df.head()

home       busca  logado  comprou
0     0  algoritmos       1        1
1     0        java       0        1
2     1  algoritmos       0        1
3     1        ruby       1        0
4     1        ruby       0        1

In [7]:
df.shape

(1000, 4)

In [8]:
df.columns.ravel()

array(['home', 'busca', 'logado', 'comprou'], dtype=object)

In [9]:
Y = df['comprou']
Y

0      1
1      1
2      1
3      0
4      1
      ..
995    0
996    1
997    1
998    1
999    0
Name: comprou, Length: 1000, dtype: int64

In [10]:
X = df[['home', 'busca', 'logado']]
X

home       busca  logado
0       0  algoritmos       1
1       0        java       0
2       1  algoritmos       0
3       1        ruby       1
4       1        ruby       0
..    ...         ...     ...
995     0        ruby       0
996     0        ruby       0
997     0        java       1
998     1  algoritmos       0
999     0        ruby       1

[1000 rows x 3 columns]

In [11]:
type(Y)

pandas.core.series.Series

In [12]:
type(X)

pandas.core.frame.DataFrame

In [13]:
Xdummies = pd.get_dummies(X) # 'one hot encoding' no pandas: fácil
Ydummies = Y # não tem variáveis categóricas

In [14]:
Ydummies

0      1
1      1
2      1
3      0
4      1
      ..
995    0
996    1
997    1
998    1
999    0
Name: comprou, Length: 1000, dtype: int64

In [15]:
Xdummies

home  logado  busca_algoritmos  busca_java  busca_ruby
0       0       1                 1           0           0
1       0       0                 0           1           0
2       1       0                 1           0           0
3       1       1                 0           0           1
4       1       0                 0           0           1
..    ...     ...               ...         ...         ...
995     0       0                 0           0           1
996     0       0                 0           0           1
997     0       1                 0           1           0
998     1       0                 1           0           0
999     0       1                 0           0           1

[1000 rows x 5 columns]

In [16]:
# transformando em arrays para facilitar o trabalho:

X = Xdummies.values
Y = Ydummies.values

In [17]:
X

array([[0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0],
       ...,
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 0, 1]])

In [18]:
Y

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,

In [19]:
X.shape

(1000, 5)

In [20]:
Y.shape

(1000,)

In [21]:
tamanho_de_treino = int(0.9 * len(Y))
tamanho_de_teste = int(len(Y)-tamanho_de_treino)

In [22]:
Xtreino = X[:tamanho_de_treino]
Ytreino = Y[:tamanho_de_treino]
Xteste = X[-tamanho_de_teste:]
Yteste = Y[-tamanho_de_teste:]

In [23]:
from sklearn.naive_bayes import MultinomialNB
modelo = MultinomialNB()
modelo.fit(Xtreino, Ytreino)
resultado = modelo.predict(Xteste)

# calculando acurácia na mão
diferencas = resultado - Yteste
acertos = [d for d in diferencas if d == 0]
acuracia = 100.0*len(acertos)/len(Yteste)
print(acuracia)

82.0


In [24]:
# utilizando função do sklearn

from sklearn.metrics import accuracy_score
accuracy_score(Yteste, resultado)

0.82

In [28]:
import numpy as np
zeros = np.zeros(100)
uns = np.ones(100)

In [29]:
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
len(Yteste)

100

In [31]:
diferencas_zero = Yteste - zeros
acertos_zero = [d for d in diferencas_zero if d == 0]
acuracia_zero = 100.0 * len(acertos_zero) / len(Yteste)
print(acuracia_zero)

18.0


In [32]:
diferencas_um = Yteste - uns
acertos_um = [d for d in diferencas_um if d == 0]
acuracia_um = 100.0 * len(acertos_um) / len(Yteste)
print(acuracia_um)

82.0


In [34]:
predicao = modelo.predict(Xteste)

In [35]:
predicao # veja, o modelo está predizendo tudo como "1"

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
# outra maneira de verificar quantos elementos são 1 ou 0:

print(Y[Y==0])
print(len(Y[Y==0]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
168


In [38]:

print(Y[Y==1])
print(len(Y[Y==1]))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [41]:
# Isso é um teste
Y==0

array([False, False, False,  True, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True, False, False, False, False,  True,  True, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False,  True,  True, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True,  True,

In [42]:
sum(Y==0)

168

In [44]:
from collections import Counter

In [45]:
Counter(Y)

Counter({0: 168, 1: 832})

In [48]:
max(Counter(Y).values())

832

In [50]:
min(Counter(Y).values())

168